# SIXTE CI/CD configuration
#
# Triggers and jobs that are then run:
# * Changes pushed to any branch -> build, test
# * Changes pushed to master     -> build, test, deploy
# * Tag pushed to any branch     -> build, update
# * Triggerd by SIMPUT pipeline  -> build, test


default:
  before_script:
    - source /software/profile.in
    - export SIMPUT=/userdata/data/sixte/simputsoft
    - export SIXTE=`pwd`
    - export HEADASNOQUERY=
    - export HEADASPROMPT=/dev/null
  after_script:
    # Remove artifacts from failed make distcheck
    - chmod u+w -R sixte-*

stages:
  - build
  - test
  - deploy
  - update

build:
  stage: build
  script:
    - autoreconf --install --force
    - ./configure --prefix=$SIXTE --with-simput=$SIMPUT
    - make
    - make install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "trigger"
  artifacts:
    expire_in: 30 min
    paths:
      - ./*


test:
  stage: test
  script:
    - . $SIXTE/sixte-install.sh
    - module load conda
    - conda activate
    - ln -sf /home/sixte/instruments.git/instruments share/sixte/instruments
    - make check
    - make test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "trigger"

deploy:
  stage: deploy
  dependencies: []
  script:
    - git push /data/git/sixt.git HEAD:master
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

update:
  stage: update
  dependencies:
    - build
  script:
    - make distcheck
    - rsync -vhu sixte-?.?.?*.tar.gz /data/www/sixte_archive/sixte/
  rules:
    - if: $CI_COMMIT_TAG
