#! /usr/bin/env python3

import subprocess
import sys
sys.path.append('../scripts/')
import sixte

# initialize default variables
defvar = sixte.defvar
dir="data/dummy"
tool = 'PHOIMG'

fin=f"data/refdata/{defvar.prefix_refdata}{defvar.fname_pholist}"
fout = f"{defvar.prefix_dummy}{defvar.fname_implist}"

file1=f"data/refdata/{defvar.prefix_refdata}{defvar.fname_implist}"
file2=fout


print(f'   *** testing {tool}  *** ')

ret_val = sixte.phoimg(fin,fout,defvar.xml,
                       logfile=defvar.log,
                       prefix=defvar.prefix_dummy,test=1)

sixte.check_returncode(ret_val,tool)

sixte.check_fdiff(file1,file2,tool)

sixte.clean_output()


