#! /usr/bin/env python3

import subprocess
import sys
sys.path.append('../scripts/')
import sixte

sixte.check_pythonversion(3,6)

from astropy.io import fits

# TEST OPTIONS

background = "yes"  ## switch the background on
# point away from the simput file (RA=0,Dec=0)
ra_outside = sixte.STDTEST.RA + 3.0
dec_outside = sixte.STDTEST.Dec + 3.0
exposure = 1000


xmllist = [sixte.STDTEST.xml,sixte.STDTEST.xml_eventmode]
testlist = ['pha_timemode','pha_eventmode']

for ii in range(len(xmllist)):

    defpath = sixte.defpath(subtestname=testlist[ii])

    print(f'   *** testing {defpath.testname}  *** ')

    ret_val = sixte.runsixt(xmllist[ii],
                            prefix='',
                            implist=defpath.testname_implist,
                            rawdata=defpath.testname_rawlist,
                            evtfile=defpath.testname_evtlist,
                            ra=ra_outside,
                            dec=dec_outside,
                            logfile=defpath.log,
                            expos=exposure,
                            background=background,
                            test=1)

    sixte.check_returncode(ret_val,defpath.fullname)

    sixte.check_fdiff( defpath.ref_path + defpath.refname_evtlist,
                       defpath.testname_evtlist,
                       defpath.fullname)



# clean output
sixte.clean_output()







