#! /usr/bin/env python3

import subprocess
import sys
sys.path.append('../scripts/')
import sixte

# initialize default variables
defvar = sixte.defvar
dir="data/dummy"
tool = 'GENDETSIM'

fin=f"data/refdata/{defvar.prefix_refdata}{defvar.fname_implist}"
fout = f"{defvar.prefix_dummy}{defvar.fname_rawlist}"

file1=f"data/refdata/{defvar.prefix_refdata}{defvar.fname_rawlist}"
file2=fout


print(f'   *** testing {tool}  *** ')

ret_val = sixte.gendetsim(fin,fout,defvar.xml,
                       logfile=defvar.log,
                       test=1)

sixte.check_returncode(ret_val,tool)

sixte.check_fdiff(file1,file2,tool)

#sixte.clean_output()


