#! /usr/bin/env python3

import subprocess
import sys
sys.path.append('../scripts/')
import sixte

sixte.check_pythonversion(3,6)

from astropy.io import fits

# initialize default variables
defvar = sixte.defvar
tool = 'GENDETSIM'

fin  = f"data/refdata/{defvar.prefix_refdata}{defvar.fname_implist}"
fout = f"{defvar.prefix_dummy}{defvar.fname_rawlist}"

reffile1=f"data/refdata/{defvar.prefix_refdata}{defvar.fname_rawlist}"
reffile2=f"data/refdata/{defvar.prefix_refdata}raw_eventreadout.fits"

def check_dummy_xml(file,tool):
    with  fits.open(file) as hdul:
        data = hdul[1].data

        status=0

        mrawx = data.field('rawx').mean()
        if  (abs(mrawx-4) > 1e-9):
            print( ' *** error : RAWX should be always 4, but is {:0.6f} on average'.format(mrawx))
            status=1

        # RAWY has to be off, as a few counts are during the readout ('readout streak'), which
        # is in this direction
        mrawy = data.field('rawy').mean()
        if  (abs(mrawy-4) < 1e-9):
            print( ' *** error : RAWY should be slightly off from 4, but is exactly 4')
            status=1

        if  (abs(mrawy-4) > 0.5):
            print( ' *** error : RAWY should be close to value 4, but with {:0.6f} it is too far off'.format(mrawy))
            status=1

    if (status!=0):
        exit(1)
    else:
        print(f'{tool}: checking RAWX/Y from dummy XML File SUCCESSFUL')
        return 0;


print(f'   *** testing {tool}  *** ')

# STANDARD TEST: TIME READOUT
tooltime = tool+" [TIME readout]"
ret_val = sixte.gendetsim(fin,fout,defvar.xml,
                       logfile=defvar.log,
                       test=1)

sixte.check_returncode(ret_val,tooltime)

sixte.check_fdiff(reffile1,fout,tooltime)

check_dummy_xml(fout,tooltime)

sixte.clean_output()

# EVENT READOUT TEST
toolevent = tool+" [EVENT readout]"
ret_val = sixte.gendetsim(fin,fout,
                          defvar.xml_path+"default_eventreadout.xml",
                          logfile=defvar.log,
                          test=1)

sixte.check_returncode(ret_val,toolevent)

sixte.check_fdiff(reffile2,fout,toolevent)

sixte.clean_output()







